### ISSUE TITLE
The Terasort results become slow, if running with more reduce tasks.

### ISSUE THREAD

**Issue by dolphinruru** [Mellanox/UDA#20]
Hi,

I run the Terasort 1TB, then compare the the results between UDA enabled and disabled. 
The UDA enabled but Terasort 1TB results didn't improve, if more than 10 reduce tasks applied when running Terasort. Please refer the results as follows.

[Environment]
Distribution: HDP-2.3.4
Hadoop: 2.7.1
UDA: 3.4.1

[Terasort UDA Enabled]
reduce tasks 1/6/10/20 : 13690/4530/**6263/6274** (seconds)

[Terasort UDA Disabled]
reduce tasks 1/6/10/20 : 36262/6991/**3439/2335** (seconds)

Why the more reduce tasks but lower performance?? How can the UDA still take effect, the performance is still improved when running with more reduce tasks?? 
Please kindly provide the suggestions, thanks!!

**Comment by liranoz12** [comment]
Hi,

Enabling UDA cause the reducers to consume additional amount of memory compared to the regular Hadoop flow.
Hence, As the amount of the reducers increases, the amount of the memory allocated for the reducers should be increased.
Low amount of memory may cause the reduce stage to be handled in two phases (which can explain to performance degradation).
Please follow UDA tuning recommendations: https://github.com/Mellanox/UDA/wiki/Tuning-Recommendations-for-YARN---Hadoop-2
If it does not help, try to increase the amount of memory allocated for the reducers.

Liran.
